package mn.navmn.app.qa

import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.TestScope
import kotlinx.coroutines.test.runCurrent
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import mn.navmn.app.background.restore.RestoreManager
import mn.navmn.app.background.restore.RestoreRules
import mn.navmn.app.background.restore.RestoreStore
import mn.navmn.app.background.restore.StoredRecord
import mn.navmn.app.engine.GuidanceEvent
import mn.navmn.app.engine.Trip
import mn.navmn.app.geo.Geo
import mn.navmn.app.geo.LatLon
import mn.navmn.app.i18n.Lang
import mn.navmn.app.i18n.StringKey
import mn.navmn.app.route.RouteOutcome
import mn.navmn.app.route.RouteProcessor
import mn.navmn.app.route.TravelMode
import mn.navmn.app.settings.ThemeChoice
import mn.navmn.app.support.FakeRouteParser
import mn.navmn.app.support.Fixtures
import mn.navmn.app.support.HostFerrostar
import mn.navmn.app.support.Replay
import mn.navmn.app.support.TestStrings
import mn.navmn.app.support.Tracks
import mn.navmn.app.theme.sun.SunCalc
import mn.navmn.app.theme.sun.SunTimes
import mn.navmn.app.theme.sun.ThemeResolver
import mn.navmn.app.voiceplan.PromptClass
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.time.Instant
import java.time.LocalDate
import java.util.TimeZone

/**
 * QA tests for NAV-012 (test plan docs/qa/test-plans/NAV-012.md, light-QA run 1). Each test names its TC and AC.
 *  - TC-H01 / TC-H02 (AC 40, 41, 44): the on-device sun function against the official NOAA Solar Calculator fixture
 *    `tests/android/nav012/noaa-sun-fixture.json` (generated by `tests/android/nav012/noaa/make_sun_fixture.mjs` from
 *    NOAA's own calculation code), in several device time zones.
 *  - TC-D07 / TC-D08 (AC 19): restore on the recorded NAV-005 G10 route (divided Peace Ave with a U-turn, the return
 *    carriageway runs ~23 m from the outbound one) through the REAL Ferrostar session: the one restore prompt must be
 *    for the next manoeuvre from the true position, also when the first good fix has no usable bearing (standing still,
 *    the usual moment to reopen the app).
 *  - TC-D09 (AC 24): the crash-loop limit end to end through [RestoreManager] across simulated process deaths.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class QaNav012Test {
    @get:Rule val tmp = TemporaryFolder()

    private val mn = TestStrings.of(Lang.MN)

    // ------------------------------------------------------------------------------------------------ sun (H)

    private val fixture: JsonObject by lazy { Json.parseToJsonElement(repoFile("tests/android/nav012/noaa-sun-fixture.json").readText()).jsonObject }

    private data class Row(val point: String, val lat: Double, val lon: Double, val date: LocalDate, val rise: Instant, val set: Instant)

    private val rows: List<Row> by lazy {
        fixture["rows"]!!.jsonArray.map { it.jsonObject }.map {
            Row(
                it["point"]!!.jsonPrimitive.content,
                it["lat"]!!.jsonPrimitive.double,
                it["lon"]!!.jsonPrimitive.double,
                LocalDate.parse(it["localDate"]!!.jsonPrimitive.content),
                Instant.parse(it["sunriseUtc"]!!.jsonPrimitive.content),
                Instant.parse(it["sunsetUtc"]!!.jsonPrimitive.content),
            )
        }
    }

    private fun <T> inZone(id: String, block: () -> T): T {
        val saved = TimeZone.getDefault()
        TimeZone.setDefault(TimeZone.getTimeZone(id))
        try {
            return block()
        } finally {
            TimeZone.setDefault(saved)
        }
    }

    /**
     * TC-H01 (AC 40): sunrise and sunset for P1, X1, K1, Z1 on the four AC 40 dates within ±2 min of the NOAA Solar
     * Calculator. The local date (Asia/Ulaanbaatar or Asia/Hovd) is the date of the solar day; the app computes in UTC
     * around that day's solar noon. Run in three device time zones (AC 41: the zone must not change the result).
     */
    @Test
    fun tcH01_noaaFixtureFourPointsFourDatesWithinTwoMinutes() {
        assertEquals("fixture rows", 16, rows.size)
        val tol = fixture["toleranceMinutes"]!!.jsonPrimitive.int.toDouble()
        val p = ArrayList<String>()
        var worst = 0.0
        for (zone in listOf("UTC", "Asia/Ulaanbaatar", "Asia/Hovd", "America/Los_Angeles")) inZone(zone) {
            for (r in rows) {
                val t = SunCalc.sunTimes(r.date, r.lat, r.lon)
                if (t !is SunTimes.Rise) {
                    p += "$zone ${r.point} ${r.date}: $t, NOAA has a sunrise and a sunset"
                    continue
                }
                val dr = SunCalc.minutesBetween(t.sunrise, r.rise)
                val ds = SunCalc.minutesBetween(t.sunset, r.set)
                worst = maxOf(worst, dr, ds)
                if (dr > tol) p += "$zone ${r.point} ${r.date}: sunrise ${t.sunrise} vs NOAA ${r.rise} (${"%.2f".format(dr)} min)"
                if (ds > tol) p += "$zone ${r.point} ${r.date}: sunset ${t.sunset} vs NOAA ${r.set} (${"%.2f".format(ds)} min)"
            }
        }
        println("TC-H01 worst deviation from NOAA: ${"%.3f".format(worst)} min over ${rows.size * 2} values x 4 zones")
        assertTrue(p.joinToString("\n"), p.isEmpty())
    }

    /**
     * TC-H02 (AC 41, 44): the theme decision itself ([SunCalc.isDay] → [ThemeResolver] «Автомат») flips at the NOAA
     * times: night 3 min before NOAA sunrise, day 3 min after; day 3 min before NOAA sunset, night 3 min after. Same
     * result in every device time zone. «Өдрийн горим» / «Шөнийн горим» ignore the sun (AC 43).
     */
    @Test
    fun tcH02_autoThemeFlipsAtTheNoaaTimesInEveryTimeZone() {
        val p = ArrayList<String>()
        val margin = 3 * 60_000L
        for (zone in listOf("UTC", "Asia/Hovd", "Pacific/Kiritimati", "America/Los_Angeles")) inZone(zone) {
            for (r in rows) {
                fun night(at: Instant) = ThemeResolver.night(ThemeChoice.AUTO, !SunCalc.isDay(at, r.lat, r.lon))
                val checks = listOf(
                    Triple("rise-3", r.rise.minusMillis(margin), true),
                    Triple("rise+3", r.rise.plusMillis(margin), false),
                    Triple("set-3", r.set.minusMillis(margin), false),
                    Triple("set+3", r.set.plusMillis(margin), true),
                )
                for ((name, at, expectNight) in checks) {
                    if (night(at) != expectNight) p += "$zone ${r.point} ${r.date} $name ($at): night=${night(at)}, expected $expectNight"
                }
                if (ThemeResolver.night(ThemeChoice.DAY, true)) p += "DAY follows the sun"
                if (!ThemeResolver.night(ThemeChoice.NIGHT, false)) p += "NIGHT follows the sun"
            }
        }
        assertTrue(p.joinToString("\n"), p.isEmpty())
    }

    // ------------------------------------------------------------------------------------------- restore (D)

    /** G10 restore setup: a point on the return carriageway after the U-turn, ≤ 50 m from the outbound carriageway. */
    private class G10Restore(val r: Replay, val restoreAt: Double, val uturnAlong: Double, val length: Double, val gapToOutbound: Double)

    private fun g10(): G10Restore {
        val r = Replay(QaGpx.routeBytes("G10"), TravelMode.CAR, Lang.MN)
        val plan = r.initial.plan
        val oracle = RouteOracle(plan)
        assertEquals("fixture: G10 has depart, U-turn, arrive", 3, plan.steps.size)
        val uturnAlong = oracle.maneuverAlong[1]
        val line = plan.geometry
        val length = Geo.length(line)
        val restoreAt = uturnAlong + (length - uturnAlong) * 0.6
        val outbound = ArrayList<LatLon>()
        var d = 0.0
        while (d < uturnAlong - 40.0) {
            outbound += Geo.along(line, d)
            d += 5.0
        }
        val gap = Geo.distanceToLine(Geo.along(line, restoreAt), outbound)
        assertTrue("fixture: restore point ${gap.toInt()} m from the outbound carriageway (needs <= 50 m)", gap <= 50.0)
        return G10Restore(r, restoreAt, uturnAlong, length, gap)
    }

    private fun restoreProblems(g: G10Restore, firstFixAt: Long): List<String> {
        val r = g.r
        val p = ArrayList<String>()
        val uturnText = mn[StringKey.MANEUVER_UTURN]
        val start = r.log.firstNotNullOfOrNull { Regex("restore start step (\\d+)").find(it)?.groupValues?.get(1)?.toInt() }
        if (start != 1) p += "AC 19: restore start step $start (the true position is on step 1, after the U-turn)"
        val early = r.spoken.filter { it.first in firstFixAt..firstFixAt + 3_000 && it.second.cls == PromptClass.MANEUVER }
        if (early.size != 1) p += "AC 19: ${early.size} manoeuvre prompts within 3 s of the first good fix: ${early.map { it.second.text }}"
        early.filter { it.second.maneuver?.second == 1 }.forEach { p += "AC 19: restore prompt is for the U-turn already made: «${it.second.text}»" }
        r.spoken.filter { it.second.maneuver?.second == 1 || it.second.text.lowercase().contains(uturnText.lowercase().substringBefore(" ")) }.forEach {
            p += "AC 19: U-turn prompt after the restore at ${it.first / 1000.0} s: «${it.second.text}»"
        }
        if (r.requests.isNotEmpty()) p += "AC 19/20: ${r.requests.size} route requests on the stored route"
        val arrivals = r.events.count { it.second == GuidanceEvent.Arrived }
        if (arrivals != 1) p += "AC 19: $arrivals arrivals (expected 1 at the end of the stored route)"
        return p
    }

    /**
     * TC-D07 (AC 19): restore while STANDING on the G10 return carriageway (first good fixes: speed 0, no bearing, as
     * when the driver reopens the app at a red light), then drive on to the destination. Expected: start step 1 (after
     * the U-turn), exactly one prompt for the next manoeuvre (the arrival), never the U-turn again, 0 requests, one
     * arrival.
     */
    @Test
    fun tcD07_g10RestoreStandingOnTheReturnCarriageway() {
        HostFerrostar.require()
        val g = g10()
        val line = g.r.initial.plan.geometry
        val at = Geo.along(line, g.restoreAt)
        val standing = (1..4).map { Tracks.fix(at, it * 1_000L, null, 0.0) }
        val driving = Tracks.along(line, 8.0, t0 = 5_000, fromM = g.restoreAt + 8.0)
        g.r.run(standing + driving, tailMs = 10_000, restoredAt = 0)
        println("TC-D07 restore point ${g.restoreAt.toInt()} m along (U-turn at ${g.uturnAlong.toInt()} m, route ${g.length.toInt()} m), ${"%.1f".format(g.gapToOutbound)} m from the outbound carriageway")
        println("TC-D07 log: " + g.r.log.filter { it.startsWith("restore") })
        println("TC-D07 spoken: " + g.r.spoken.map { "${it.first / 1000.0}s ${it.second.maneuver} ${it.second.text}" })
        val p = restoreProblems(g, standing.first().elapsedMs)
        assertTrue(p.joinToString("\n"), p.isEmpty())
    }

    /** TC-D08 (AC 19, control for TC-D07): the same restore while DRIVING (usable bearing on the first good fix). */
    @Test
    fun tcD08_g10RestoreDrivingOnTheReturnCarriageway() {
        HostFerrostar.require()
        val g = g10()
        val line = g.r.initial.plan.geometry
        val driving = Tracks.along(line, 8.0, t0 = 1_000, fromM = g.restoreAt)
        g.r.run(driving, tailMs = 10_000, restoredAt = 0)
        println("TC-D08 log: " + g.r.log.filter { it.startsWith("restore") })
        println("TC-D08 spoken: " + g.r.spoken.map { "${it.first / 1000.0}s ${it.second.maneuver} ${it.second.text}" })
        val p = restoreProblems(g, driving.first().elapsedMs)
        assertTrue(p.joinToString("\n"), p.isEmpty())
    }

    /**
     * TC-D10 (AC 19, ADR-0013 Amendment 2 steps 3–4, run 3): the TC-D07 restore while STANDING on the G10 return
     * carriageway, but with a poor (still "good", ≤ 25 m) accuracy of 25 m, as is usual for a stationary phone between
     * buildings. The tie margin max(10 m, 25 m) then covers the outbound carriageway (~22.5 m away), so the start step
     * may be the earlier one (the residual risk the ADR accepts). Required: the one bearing re-check, at the first
     * driving fix, moves the session to step 1 with 0 route requests; no U-turn prompt after that; at most one extra
     * manoeuvre prompt in total (ADR Amendment 2 step 4); exactly one arrival at the destination.
     */
    @Test
    fun tcD10_g10RestoreStandingWithPoorAccuracyIsCorrectedByTheBearingRecheck() {
        HostFerrostar.require()
        val g = g10()
        val r = g.r
        val line = r.initial.plan.geometry
        val at = Geo.along(line, g.restoreAt)
        val standing = (1..4).map { Tracks.fix(at, it * 1_000L, null, 0.0, accuracy = 25.0) }
        val driving = Tracks.along(line, 8.0, t0 = 5_000, fromM = g.restoreAt + 8.0)
        r.run(standing + driving, tailMs = 10_000, restoredAt = 0)
        val log = r.log.filter { it.startsWith("restore") }
        println("TC-D10 log: $log")
        println("TC-D10 spoken: " + r.spoken.map { "${it.first / 1000.0}s ${it.second.maneuver} ${it.second.text}" })
        val p = ArrayList<String>()
        val start = log.firstNotNullOfOrNull { Regex("restore start step (\\d+)").find(it)?.groupValues?.get(1)?.toInt() }
        if (start == null) p += "no restore start step logged"
        if (start == 0 && log.none { it.contains("re-check: step 0 -> 1") }) p += "start step 0 was not corrected to step 1 by the bearing re-check: $log"
        val firstDriving = driving.first().elapsedMs
        r.spoken.filter { it.first > firstDriving && it.second.maneuver?.second == 1 }
            .forEach { p += "U-turn prompt after the bearing re-check at ${it.first / 1000.0} s: «${it.second.text}»" }
        val maneuverPrompts = r.spoken.filter { it.second.cls == PromptClass.MANEUVER }
        // One restore prompt + at most one re-check catch-up; the arrival itself is the next manoeuvre.
        val nonArrival = maneuverPrompts.filter { it.second.maneuver?.second != 2 }
        if (nonArrival.size > 1) p += "more than one extra manoeuvre prompt: ${nonArrival.map { it.second.text }}"
        if (r.requests.isNotEmpty()) p += "AC 19/20: ${r.requests.size} route requests on the stored route"
        val arrivals = r.events.count { it.second == GuidanceEvent.Arrived }
        if (arrivals != 1) p += "AC 19: $arrivals arrivals (expected 1)"
        assertTrue(p.joinToString("\n"), p.isEmpty())
    }

    /**
     * TC-D09 (AC 24, 21): crash loop across simulated process deaths through [RestoreManager] (each "process" is a new
     * manager on the same directory; a restore records itself exactly as [mn.navmn.app.engine.GuidanceSession.restore]
     * does). Interruptions at 2, 4 and 6 min: restores 1 and 2 happen, the third interruption deletes the record and
     * opens the map screen (no restore). Control: a third interruption 10+ min after the first restore restores.
     */
    @Test
    fun tcD09_crashLoopLimitAcrossProcessDeaths() {
        val t0 = 1_790_000_000_000L
        val route = (RouteProcessor(FakeRouteParser()).process(Fixtures.route("p1-p3-car-mn.json"), 0) as RouteOutcome.Ok).route
        val trip = Trip(LatLon(47.8858, 106.9173), "Зайсан толгой", TravelMode.CAR, avoidUnpaved = false)
        // The first «Эхлэх» write must land before the first interruption: use a scope we can flush.
        fun startedDir(name: String): File {
            val dir = File(tmp.root, name)
            val scope = TestScope(StandardTestDispatcher())
            val m = RestoreManager(RestoreStore(dir), null, { t0 }, scope)
            m.onGuidanceStarted(trip, route, Lang.MN)
            scope.runCurrent()
            assertTrue("record written at «Эхлэх»", RestoreStore(dir).read() is StoredRecord.Present)
            return dir
        }
        fun restoreOnly(dir: File, interruptions: List<Long>): List<RestoreRules.Decision> {
            val decisions = ArrayList<RestoreRules.Decision>()
            for (at in interruptions) {
                val now = t0 + at
                val scope = TestScope(StandardTestDispatcher())
                val m = RestoreManager(RestoreStore(dir), null, { now }, scope)
                val d = m.decide(sessionAlive = false, locationOk = true)
                decisions += d
                if (d is RestoreRules.Decision.Restore) {
                    m.onGuidanceStarted(trip, route, Lang.MN, restored = RestoreRules.afterRestore(d.meta, now))
                    scope.runCurrent()
                } else if (d is RestoreRules.Decision.DeleteSilently) {
                    m.delete()
                }
            }
            return decisions
        }
        val loopDir = startedDir("loop")
        val loop = restoreOnly(loopDir, listOf(2 * 60_000L, 4 * 60_000L, 6 * 60_000L))
        assertTrue("1st interruption restores: ${loop[0]}", loop[0] is RestoreRules.Decision.Restore)
        assertTrue("2nd interruption restores: ${loop[1]}", loop[1] is RestoreRules.Decision.Restore)
        assertEquals("3rd interruption within 10 min", RestoreRules.Decision.DeleteSilently(RestoreRules.Reason.LOOP_LIMIT), loop[2])
        assertFalse("record deleted (map screen, no notice)", loopDir.exists())

        val slowDir = startedDir("slow")
        val slow = restoreOnly(slowDir, listOf(2 * 60_000L, 4 * 60_000L, 13 * 60_000L))
        assertTrue("restores at 2, 4 and 13 min (the 2 min restore is outside the 10 min window at 13 min): $slow", slow.all { it is RestoreRules.Decision.Restore })
        // AC 21: 31 min after the last heartbeat the record is deleted silently.
        val expired = restoreOnly(slowDir, listOf(13 * 60_000L + 30 * 60_000L + 1))
        assertEquals(RestoreRules.Decision.DeleteSilently(RestoreRules.Reason.EXPIRED), expired.single())
        assertFalse(slowDir.exists())
    }
}
