#!/usr/bin/env python3
"""Regenerates mobile/android/THIRD_PARTY_NOTICES.md (NAV-005, ADR-0009 §6 and §11).

Reads the resolved debug runtime classpath (`./gradlew :app:dependencies --configuration debugRuntimeClasspath`) and the
licence of every artifact from its POM (and parent POMs) in the Gradle cache. Bundled assets and the hand-checked
entries are listed in HEADER/ASSETS below. Run from mobile/android:  python3 tools/gen-third-party-notices.py
"""
import glob, os, re, subprocess, sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.expanduser("~/.gradle/caches/modules-2/files-2.1")
NS = {"m": "http://maven.apache.org/POM/4.0.0"}

def deps():
    out = subprocess.run(["./gradlew", "-q", ":app:dependencies", "--configuration", "debugRuntimeClasspath", "-Pnav.hostFerrostar=off"],
                         cwd=ROOT, capture_output=True, text=True, check=True).stdout
    found = set()
    for line in out.splitlines():
        m = re.search(r"([\w.\-]+):([\w.\-]+):([\w.\-]+)(?: -> ([\w.\-]+))?", line)
        if not m or "project :" in line:
            continue
        g, a, v, override = m.groups()
        if line.rstrip().endswith("(c)") or line.rstrip().endswith("(*)") and False:
            pass
        found.add((g, a, override or v))
    return sorted(found)

def pom(g, a, v):
    hits = glob.glob(os.path.join(CACHE, g, a, v, "*", f"{a}-{v}.pom"))
    if not hits:
        return None
    try:
        return ET.parse(hits[0]).getroot()
    except ET.ParseError:
        return None

def text(el, path):
    x = el.find(path, NS) if el is not None else None
    return x.text.strip() if x is not None and x.text else None

def licence(g, a, v, depth=0):
    root = pom(g, a, v)
    if root is None:
        return None, None
    names = [l.findtext("m:name", default="", namespaces=NS).strip() for l in root.findall("m:licenses/m:license", NS)]
    url = text(root, "m:url") or text(root, "m:scm/m:url")
    if names:
        return " / ".join(n for n in names if n), url
    parent = root.find("m:parent", NS)
    if parent is not None and depth < 5:
        lic, purl = licence(text(parent, "m:groupId"), text(parent, "m:artifactId"), text(parent, "m:version"), depth + 1)
        return lic, url or purl
    return None, url

HEADER = """# Third-party notices (mobile/android/)

Generated by `tools/gen-third-party-notices.py` (NAV-005, ADR-0009 §6, §11). Do not edit the tables by hand.

The debug APK ships (a) assets copied at build time from the vendored web copy, (b) the app's own style JSON generated from
the web style code, and (c) the runtime libraries below. Build and test tools (Gradle, AGP, Kotlin compiler, KSP,
Robolectric, JUnit, MockWebServer, the host Ferrostar build) are not shipped and are not listed. No GPL component.

## 1. Bundled assets

| Asset | Path in the APK | Source | Licence |
|---|---|---|---|
| Noto Sans Regular / Medium / Italic glyph PBFs | `assets/fonts/<fontstack>/<range>.pbf` | copied at build time from `web/public/fonts/` (basemaps-assets commit in `web/public/fonts/BASEMAPS_ASSETS_COMMIT`) | SIL Open Font License 1.1 (`assets/fonts/OFL.txt`; full text in `web/THIRD_PARTY_NOTICES.md` §3.1) |
| Map icon sprites `light`, `dark` | `assets/sprites/v4/` | copied at build time from `web/public/sprites/v4/` | MIT (tangrams/icons) and CC0 (Protomaps design); full texts in `web/THIRD_PARTY_NOTICES.md` §3.2–3.3 |
| Basemap style JSON (day, night) | `assets/style/basemap-*.json` | generated by `web/scripts/export-native-style.mjs` from `@protomaps/basemaps` 5.7.2 + `docs/design/tokens.json` | BSD-3-Clause code, CC0 visual design (`web/THIRD_PARTY_NOTICES.md` §3.3) |
| Manoeuvre and control icons | `res/drawable/ic_*.xml` | the project's own paths (same artwork as `web/src/ui/icons.ts`, `routeIcons.ts`) | project-owned, no third-party artwork |
| Chime | generated in code (`voice/VoiceSelection.kt` ChimePcm) | sine tones, no samples | project-owned |

Map data is not bundled: tiles are read at runtime from the gateway (© OpenStreetMap contributors, ODbL; low-zoom
landcover © ESA WorldCover, CC BY 4.0). Both credits are shown on the map screens (AC 2).

## 2. Runtime libraries (debug runtime classpath)

JNA (`net.java.dev.jna:jna`) is dual-licensed Apache-2.0 OR LGPL-2.1 and is used under **Apache-2.0** (ADR-0009 §11).
Ferrostar `core` bundles `libferrostar.so` (BSD-3-Clause, built from https://github.com/stadiamaps/ferrostar).
MapLibre Native bundles `libmaplibre.so` (BSD-2-Clause).

| Group | Artifact | Version | Licence | Project URL |
|---|---|---|---|---|
"""

# POMs without a <licenses> element, checked by hand.
KNOWN = {("javax.inject", "javax.inject"): ("Apache-2.0", "https://github.com/javax-inject/javax-inject")}

def main():
    rows = []
    missing = []
    seen = set()
    for g, a, v in deps():
        if (g, a, v) in seen:
            continue
        seen.add((g, a, v))
        lic, url = KNOWN.get((g, a)) or licence(g, a, v)
        if lic is None:
            missing.append(f"{g}:{a}:{v}")
            lic = "see project"
        rows.append(f"| `{g}` | `{a}` | {v} | {lic} | {url or ''} |")
    with open(os.path.join(ROOT, "THIRD_PARTY_NOTICES.md"), "w") as f:
        f.write(HEADER + "\n".join(rows) + "\n")
        if missing:
            f.write("\nLicence not found in the POM (checked by hand before release): " + ", ".join(missing) + "\n")
    print(f"{len(rows)} libraries; {len(missing)} without a POM licence")
    if any("GPL" in r and "LGPL" not in r and "Classpath" not in r for r in rows):
        print("GPL licence found", file=sys.stderr)
        sys.exit(1)

main()
