package mn.navmn.app.map

import android.content.Context

/**
 * ADR-0009 §6: the committed native style JSON (generated by web/scripts/export-native-style.mjs from the web
 * buildStyle) with the tiles placeholder replaced by `pmtiles://<gateway>/tiles/basemap.pmtiles`. Glyphs and sprites
 * are `asset://` URLs (the vendored web copy, synced by Gradle). No third-party host (AC 65).
 */
object MapStyle {
    const val TILES_PLACEHOLDER = "{GATEWAY_TILES_URL}"

    fun assetPath(night: Boolean) = if (night) "style/basemap-night.json" else "style/basemap-day.json"

    fun resolve(styleJson: String, pmtilesUrl: String): String {
        require(styleJson.contains(TILES_PLACEHOLDER)) { "style has no tiles placeholder" }
        return styleJson.replace(TILES_PLACEHOLDER, pmtilesUrl)
    }

    fun load(context: Context, night: Boolean, pmtilesUrl: String): String =
        resolve(context.assets.open(assetPath(night)).use { it.readBytes().decodeToString() }, pmtilesUrl)
}
