#!/bin/sh
# NAV-001 (AC 29-31): turn CORS_ALLOWED_ORIGINS into an nginx map $http_origin -> $cors_allow_origin.
#   "*"                         -> every request gets Access-Control-Allow-Origin: *
#   "http://a:5173,http://b"    -> only those exact origins are echoed back; others get no header
set -eu

out="${NGINX_ENVSUBST_OUTPUT_DIR:-/etc/nginx/conf.d}/00-cors-origins.conf"
origins="$(printf '%s' "${CORS_ALLOWED_ORIGINS:-*}" | tr -d ' ')"

{
    echo "# generated by 15-cors-origins.sh from CORS_ALLOWED_ORIGINS"
    echo 'map $http_origin $cors_allow_origin {'
    if [ "$origins" = "*" ] || [ -z "$origins" ]; then
        echo '    default "*";'
    else
        echo '    default "";'
        old_ifs=$IFS
        IFS=','
        for o in $origins; do
            [ -n "$o" ] || continue
            case "$o" in
                *'"'*|*'\'*|*';'*|*'{'*|*'}'*|*' '*)
                    echo "15-cors-origins.sh: invalid origin in CORS_ALLOWED_ORIGINS: $o" >&2
                    exit 1 ;;
            esac
            echo "    \"$o\" \$http_origin;"
        done
        IFS=$old_ifs
    fi
    echo '}'
} > "$out"

printf '{"service":"gateway","level":"info","msg":"cors origins configured","mode":"%s"}\n' \
    "$( [ "$origins" = "*" ] && echo wildcard || echo allowlist )"
